package com.isolamonte.bookingsystem.domain

import com.isolamonte.bookingsystem.db.BookingRepository
import com.isolamonte.bookingsystem.db.types.Booking
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest

//@Disabled
@SpringBootTest
class BookingServiceTests {

	@Autowired
	lateinit var bookingRepository: BookingRepository

	@Test
	fun lookupBooking() {
		// given
		val service = BookingService(bookingRepository)
		val existingBooking = Booking(null, "natalia", "2022-07-12", "MIDDAY", "MAPLE_STREET_5")

		// when
		val listOfBookings = service.listBookings()

		// then
		assertThat(listOfBookings).contains(existingBooking)
	}

	@Test
	fun fetchBookingByIdAndCancel() {
		// given
		val service = BookingService(bookingRepository)
		val listOfBookings = service.listBookings()

		//when
		/**
		 * Since the UUIDs are generated by the DB I have to fetch all the bookings
		 * and then re-fetch a specific one from the list, but this time via the UUID.
		 */
		val firstBooking = listOfBookings[0]
		val aBooking = firstBooking.id?.let { service.getBookingById(it) }

		// then
		assertThat(aBooking).isPresent

		firstBooking.id?.let { service.deleteBooking(it) }
		val deletedBooking = firstBooking.id?.let { service.getBookingById(it) }

		assertThat(deletedBooking).isNotPresent
	}

	@Test
	fun checkForBookingClash() {
		// given
		val service = BookingService(bookingRepository)
		// See `data.sql` in src/main/resources
		val existingBooking = Booking(null, "natalia", "2022-07-12", "MIDDAY", "MAPLE_STREET_5")

		// when
		val maybeClash = service.findMaybeClash(existingBooking)

		// then
		assertThat(maybeClash).isNotNull
	}

	@Test
	fun fetchNonExistingBooking() {
		// given
		val service = BookingService(bookingRepository)
		val newBooking = Booking(null, "kim", "2022-11-03", "MORNING", "MAPLE_STREET_3")

		// when
		val listOfBookings = service.listBookings()

		// then
		assertThat(listOfBookings).doesNotContain(newBooking)
	}

}
